#########################################################################
# Title:         Saltbox: Maintainerr Role                              #
# Author(s):     dabigc                                                 #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Maintainerr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    maintainerr_name: "{{ role }}"
  with_items: "{{ maintainerr_instances }}"
  loop_control:
    loop_var: role
